-- AlterTable
ALTER TABLE "runsheets" DROP COLUMN "break_1",
DROP COLUMN "break_2",
DROP COLUMN "break_3",
DROP COLUMN "break_4",
DROP COLUMN "final_depart",
DROP COLUMN "first_arrival",
DROP COLUMN "travel_time",
ADD COLUMN     "break_1_duration" INTEGER DEFAULT 15,
ADD COLUMN     "break_1_end_time" TEXT,
ADD COLUMN     "break_1_start_time" TEXT,
ADD COLUMN     "break_2_duration" INTEGER DEFAULT 30,
ADD COLUMN     "break_2_end_time" TEXT,
ADD COLUMN     "break_2_start_time" TEXT,
ADD COLUMN     "break_3_duration" INTEGER DEFAULT 15,
ADD COLUMN     "break_3_end_time" TEXT,
ADD COLUMN     "break_3_start_time" TEXT,
ADD COLUMN     "break_4_duration" INTEGER DEFAULT 15,
ADD COLUMN     "break_4_end_time" TEXT,
ADD COLUMN     "break_4_start_time" TEXT,
ADD COLUMN     "final_depart_time" TEXT,
ADD COLUMN     "first_arrival_time" TEXT,
ADD COLUMN     "travel_time_duration" TEXT;
